name: 'Expand tokens'
description: 'Replaces `__TOKENS__` with the values of equivalent environment variables in files.'
inputs:
  path:
    description: 'Path to the file or directory to process.'
    required: true
  filenames:
    description: 'Filename filter, used if path is a directory.'
  recursive:
    description: 'Whether to recursively search for files, used if path is a directory.'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'